### ISSUE TITLE
Login form doesn't submit when enter key pressed

### ISSUE THREAD

**Issue by logan-r** [hackmcgill/dashboard#839]
Tested on Windows 10 - Chrome & Firefox.
Create account page form does submit on enter key press though.

**Comment by jamesxu123** [comment]
It seems that the problem is that the button type gets switched from 'submit' to 'button' in the resulting HTML:
![image](https://user-images.githubusercontent.com/36768789/98455159-e04e9c00-213a-11eb-8234-78229a1caaad.png)

Once you manually set it in the browser it works again. I'll keep searching for a solution, but I'm quite new to React, so please let me know if you have seen this problem before or have an idea where the problem might be.

**Comment by pierreTklein** [comment]
Is the submitbtn in react actually a submit button?

**Comment by jamesxu123** [comment]
It is, and SubmitBtn seems to set `type={'submit'}`.

**Comment by jamesxu123** [comment]
Wait nevermind! I was looking at the account creation button instead of the login button. That one was indeed not set to submit.
